# -*- coding: utf-8 -*-
"""rice_UI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8htwuTpRFOAF_YatJ91OkjMGOkowyE-
"""

from google.colab import drive

!pip install gradio --quiet

import gradio as gr
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model

# ✅ Load your trained model
model_path = "/content/drive/MyDrive/best_rice_cnn.h5"  # Change if needed
model = load_model(model_path)

# ✅ Define class labels (must match your training order)
class_labels = ['bacterial_leaf_blight', 'bacterial_leaf_streak', 'bacterial_panicle_blight',
                'blast', 'brown_spot', 'dead_heart', 'downy_mildew', 'hispa', 'normal', 'tungro']

# ✅ Collect all image paths
# ✅ Prediction function
def predict_image(img):
    # Resize and preprocess image
    img = img.resize((224, 224))  # match input size of your model
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # Predict
    predictions = model.predict(img_array)
    predicted_class = class_labels[np.argmax(predictions)]
    confidence = np.max(predictions)

    return {predicted_class: float(confidence)}

# ✅ Gradio Interface
interface = gr.Interface(
    fn=predict_image,
    inputs=gr.Image(type="pil", label="Upload Rice Leaf Image"),
    outputs=gr.Label(num_top_classes=2, label="Prediction"),
    title="Rice Leaf Disease Detection",
    description="Upload an image of a rice leaf to classify it as Normal or Diseased"
)

interface.launch(debug=True)